<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Untitled.ico</ApplicationIcon>

	  <!--<PublishSingleFile>true</PublishSingleFile>-->
	  <!--<SelfContained>true</SelfContained>-->
	  <RuntimeIdentifier>win-x64</RuntimeIdentifier>
	  <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
	  <AssemblyVersion>1.0.3</AssemblyVersion>
	  <FileVersion>1.0.3</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ApplicationDefinition Remove="App.xaml" />
    <Page Include="App.xaml" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="NLog.xsd" />
    <None Remove="Resources\logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Untitled.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
    <PackageReference Include="Ical.Net" Version="5.1.0" />
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3485.44" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="NLog" Version="6.0.4" />
    <PackageReference Include="NLog.Schema" Version="6.0.4" />
    <PackageReference Include="QRCoder" Version="1.6.0" />
    <PackageReference Include="SimpleHtmlToPdf" Version="3.0.5" />
    <PackageReference Include="Velopack" Version="1.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="NLog.xsd" />
    <Resource Include="Resources\logo.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="AssemblyInfo.cs">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="nlog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\addressField.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\empty.pdf">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\footer.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\index.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Resources\mail.html">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
